In [1]:
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [2]:
dataset = pd.read_csv('diabetes-dataset.csv')
dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            2      138             62             35        0  33.6   
1            0       84             82             31      125  38.2   
2            0      145              0              0        0  44.2   
3            0      135             68             42      250  42.3   
4            1      139             62             41      480  40.7   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.127   47        1  
1                     0.233   23        0  
2                     0.630   31        1  
3                     0.365   24        1  
4                     0.536   21        0

In [3]:
dataset.shape

(2000, 9)

In [4]:
feature_names = dataset.columns
print(feature_names)

x = dataset.drop(["Outcome"],axis=1)
y=dataset["Outcome"]

X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size = 0.3, random_state=6)

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')


In [5]:
Y_test.head()

1085    0
190     0
596     0
486     0
1364    1
Name: Outcome, dtype: int64

In [6]:
# Convert into float type
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

# Converting Y to categorical.
Y_train = to_categorical(Y_train, 2)
Y_test = to_categorical(Y_test, 2)

X_train.info()
X_train.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1400 entries, 550 to 906
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               1400 non-null   float32
 1   Glucose                   1400 non-null   float32
 2   BloodPressure             1400 non-null   float32
 3   SkinThickness             1400 non-null   float32
 4   Insulin                   1400 non-null   float32
 5   BMI                       1400 non-null   float32
 6   DiabetesPedigreeFunction  1400 non-null   float32
 7   Age                       1400 non-null   float32
dtypes: float32(8)
memory usage: 54.7 KB


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin        BMI  \
550          1.0    116.0           70.0           28.0      0.0  27.400000   
71           5.0    139.0           64.0           35.0    140.0  28.600000   
427          1.0    181.0           64.0           30.0    180.0  34.099998   
523          9.0    130.0           70.0            0.0      0.0  34.200001   
434          1.0     90.0           68.0            8.0      0.0  24.500000   

     DiabetesPedigreeFunction   Age  
550                     0.204  21.0  
71                      0.411  26.0  
427                     0.328  38.0  
523                     0.652  45.0  
434                     1.138  36.0

# First Model with one hidden layer with 16 neurons.

### Creating Model

In [7]:
model_1 = Sequential()
model_1.add(Dense(8, input_shape=(8,), activation='relu'))
model_1.add(Dense(16, activation='relu'))
model_1.add(Dense(8, activation='relu'))
model_1.add(Dense(2, activation='softmax'))

### Configure the model and start training

In [8]:
model_1.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

### Training the model

In [9]:
model_1.fit(X_train, Y_train, epochs=1000, batch_size=250, verbose=1, validation_split=0.2)

Epoch 1/1000
5/5 [==============================] - 1s 176ms/step - loss: 7.6512 - accuracy: 0.3518 - val_loss: 4.3851 - val_accuracy: 0.3643
Epoch 2/1000
5/5 [==============================] - 0s 9ms/step - loss: 2.9787 - accuracy: 0.3464 - val_loss: 1.8181 - val_accuracy: 0.5321
Epoch 3/1000
5/5 [==============================] - 0s 8ms/step - loss: 2.3656 - accuracy: 0.5920 - val_loss: 2.6740 - val_accuracy: 0.6607
Epoch 4/1000
5/5 [==============================] - 0s 8ms/step - loss: 2.5814 - accuracy: 0.6339 - val_loss: 1.8724 - val_accuracy: 0.6429
Epoch 5/1000
5/5 [==============================] - 0s 8ms/step - loss: 1.6563 - accuracy: 0.5464 - val_loss: 1.4050 - val_accuracy: 0.3679
Epoch 6/1000
5/5 [==============================] - 0s 9ms/step - loss: 1.5427 - accuracy: 0.3643 - val_loss: 1.5185 - val_accuracy: 0.3500
Epoch 7/1000
5/5 [==============================] - 0s 10ms/step - loss: 1.4170 - accuracy: 0.3625 - val_loss: 1.1276 - val_accuracy: 0.4357
Epoch 8/1000
5/5 

Epoch 59/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.5818 - accuracy: 0.6804 - val_loss: 0.6069 - val_accuracy: 0.6607
Epoch 60/1000
5/5 [==============================] - 0s 12ms/step - loss: 0.5926 - accuracy: 0.6830 - val_loss: 0.6018 - val_accuracy: 0.6643
Epoch 61/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5900 - accuracy: 0.6804 - val_loss: 0.6021 - val_accuracy: 0.6536
Epoch 62/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5783 - accuracy: 0.6866 - val_loss: 0.6030 - val_accuracy: 0.6821
Epoch 63/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.5847 - accuracy: 0.6866 - val_loss: 0.6006 - val_accuracy: 0.6679
Epoch 64/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.5824 - accuracy: 0.6857 - val_loss: 0.5987 - val_accuracy: 0.6679
Epoch 65/1000
5/5 [==============================] - 0s 12ms/step - loss: 0.5795 - accuracy: 0.6848 - val_loss: 0.5979 - val_accuracy: 0.6607
Epoch 66/

Epoch 117/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.5366 - accuracy: 0.7295 - val_loss: 0.5606 - val_accuracy: 0.7214
Epoch 118/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.5374 - accuracy: 0.7277 - val_loss: 0.5630 - val_accuracy: 0.7286
Epoch 119/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5353 - accuracy: 0.7241 - val_loss: 0.5608 - val_accuracy: 0.7179
Epoch 120/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.5343 - accuracy: 0.7196 - val_loss: 0.5653 - val_accuracy: 0.6893
Epoch 121/1000
5/5 [==============================] - 0s 12ms/step - loss: 0.5325 - accuracy: 0.7375 - val_loss: 0.5591 - val_accuracy: 0.7214
Epoch 122/1000
5/5 [==============================] - 0s 14ms/step - loss: 0.5347 - accuracy: 0.7223 - val_loss: 0.5663 - val_accuracy: 0.7071
Epoch 123/1000
5/5 [==============================] - 0s 15ms/step - loss: 0.5326 - accuracy: 0.7259 - val_loss: 0.5571 - val_accuracy: 0.7250
Ep

5/5 [==============================] - 0s 11ms/step - loss: 0.5004 - accuracy: 0.7464 - val_loss: 0.5474 - val_accuracy: 0.7143
Epoch 175/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.5042 - accuracy: 0.7429 - val_loss: 0.5380 - val_accuracy: 0.7536
Epoch 176/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.5012 - accuracy: 0.7607 - val_loss: 0.5492 - val_accuracy: 0.7179
Epoch 177/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4988 - accuracy: 0.7580 - val_loss: 0.5459 - val_accuracy: 0.7429
Epoch 178/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5055 - accuracy: 0.7375 - val_loss: 0.5586 - val_accuracy: 0.7179
Epoch 179/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.5075 - accuracy: 0.7643 - val_loss: 0.5654 - val_accuracy: 0.7143
Epoch 180/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.5285 - accuracy: 0.7170 - val_loss: 0.5875 - val_accuracy: 0.6821
Epoch 181/1000
5/5 

5/5 [==============================] - 0s 10ms/step - loss: 0.4787 - accuracy: 0.7607 - val_loss: 0.5182 - val_accuracy: 0.7357
Epoch 232/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4849 - accuracy: 0.7616 - val_loss: 0.5296 - val_accuracy: 0.7286
Epoch 233/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4829 - accuracy: 0.7661 - val_loss: 0.5360 - val_accuracy: 0.7357
Epoch 234/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4927 - accuracy: 0.7464 - val_loss: 0.5395 - val_accuracy: 0.7321
Epoch 235/1000
5/5 [==============================] - 0s 12ms/step - loss: 0.4848 - accuracy: 0.7670 - val_loss: 0.5305 - val_accuracy: 0.7464
Epoch 236/1000
5/5 [==============================] - 0s 12ms/step - loss: 0.4895 - accuracy: 0.7536 - val_loss: 0.5419 - val_accuracy: 0.7286
Epoch 237/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4823 - accuracy: 0.7652 - val_loss: 0.5200 - val_accuracy: 0.7464
Epoch 238/1000

5/5 [==============================] - 0s 10ms/step - loss: 0.4559 - accuracy: 0.7804 - val_loss: 0.5057 - val_accuracy: 0.7286
Epoch 289/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4541 - accuracy: 0.7759 - val_loss: 0.5052 - val_accuracy: 0.7393
Epoch 290/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4534 - accuracy: 0.7786 - val_loss: 0.5063 - val_accuracy: 0.7393
Epoch 291/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4545 - accuracy: 0.7795 - val_loss: 0.5064 - val_accuracy: 0.7321
Epoch 292/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4543 - accuracy: 0.7768 - val_loss: 0.5067 - val_accuracy: 0.7321
Epoch 293/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4527 - accuracy: 0.7768 - val_loss: 0.5050 - val_accuracy: 0.7393
Epoch 294/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4537 - accuracy: 0.7804 - val_loss: 0.5032 - val_accuracy: 0.7357
Epoch 295/1000
5/

5/5 [==============================] - 0s 9ms/step - loss: 0.4535 - accuracy: 0.7884 - val_loss: 0.5117 - val_accuracy: 0.7571
Epoch 346/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4583 - accuracy: 0.7777 - val_loss: 0.5179 - val_accuracy: 0.7357
Epoch 347/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4483 - accuracy: 0.7920 - val_loss: 0.5057 - val_accuracy: 0.7357
Epoch 348/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4418 - accuracy: 0.7830 - val_loss: 0.5009 - val_accuracy: 0.7464
Epoch 349/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4433 - accuracy: 0.7920 - val_loss: 0.5058 - val_accuracy: 0.7393
Epoch 350/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4467 - accuracy: 0.7929 - val_loss: 0.5053 - val_accuracy: 0.7464
Epoch 351/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4411 - accuracy: 0.7964 - val_loss: 0.5012 - val_accuracy: 0.7571
Epoch 352/1000
5

5/5 [==============================] - 0s 11ms/step - loss: 0.4323 - accuracy: 0.7937 - val_loss: 0.4921 - val_accuracy: 0.7464
Epoch 403/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4239 - accuracy: 0.8018 - val_loss: 0.4866 - val_accuracy: 0.7607
Epoch 404/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4273 - accuracy: 0.8036 - val_loss: 0.4935 - val_accuracy: 0.7536
Epoch 405/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4303 - accuracy: 0.7946 - val_loss: 0.5046 - val_accuracy: 0.7500
Epoch 406/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4347 - accuracy: 0.8027 - val_loss: 0.5074 - val_accuracy: 0.7571
Epoch 407/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4326 - accuracy: 0.7964 - val_loss: 0.4993 - val_accuracy: 0.7571
Epoch 408/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4244 - accuracy: 0.8062 - val_loss: 0.5001 - val_accuracy: 0.7500
Epoch 409/1000
5/5 [

Epoch 460/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4170 - accuracy: 0.8054 - val_loss: 0.4886 - val_accuracy: 0.7536
Epoch 461/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4258 - accuracy: 0.8062 - val_loss: 0.4979 - val_accuracy: 0.7607
Epoch 462/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4267 - accuracy: 0.7982 - val_loss: 0.4948 - val_accuracy: 0.7571
Epoch 463/1000
5/5 [==============================] - 0s 12ms/step - loss: 0.4246 - accuracy: 0.8009 - val_loss: 0.4802 - val_accuracy: 0.7679
Epoch 464/1000
5/5 [==============================] - 0s 12ms/step - loss: 0.4169 - accuracy: 0.8098 - val_loss: 0.4859 - val_accuracy: 0.7536
Epoch 465/1000
5/5 [==============================] - 0s 16ms/step - loss: 0.4184 - accuracy: 0.8054 - val_loss: 0.4866 - val_accuracy: 0.7500
Epoch 466/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4137 - accuracy: 0.8000 - val_loss: 0.4845 - val_accuracy: 0.7536
E

5/5 [==============================] - 0s 8ms/step - loss: 0.4100 - accuracy: 0.8062 - val_loss: 0.4768 - val_accuracy: 0.7643
Epoch 518/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4108 - accuracy: 0.7955 - val_loss: 0.4777 - val_accuracy: 0.7571
Epoch 519/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4107 - accuracy: 0.8054 - val_loss: 0.4812 - val_accuracy: 0.7571
Epoch 520/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4099 - accuracy: 0.8045 - val_loss: 0.4784 - val_accuracy: 0.7607
Epoch 521/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4081 - accuracy: 0.8116 - val_loss: 0.4787 - val_accuracy: 0.7607
Epoch 522/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4148 - accuracy: 0.8036 - val_loss: 0.5018 - val_accuracy: 0.7464
Epoch 523/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4250 - accuracy: 0.8018 - val_loss: 0.4874 - val_accuracy: 0.7571
Epoch 524/1000
5/5 

Epoch 575/1000
5/5 [==============================] - 0s 13ms/step - loss: 0.4086 - accuracy: 0.8152 - val_loss: 0.4624 - val_accuracy: 0.7643
Epoch 576/1000
5/5 [==============================] - 0s 13ms/step - loss: 0.4007 - accuracy: 0.8125 - val_loss: 0.4640 - val_accuracy: 0.7607
Epoch 577/1000
5/5 [==============================] - 0s 13ms/step - loss: 0.4013 - accuracy: 0.8232 - val_loss: 0.4656 - val_accuracy: 0.7536
Epoch 578/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4022 - accuracy: 0.8080 - val_loss: 0.4667 - val_accuracy: 0.7536
Epoch 579/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4052 - accuracy: 0.8125 - val_loss: 0.4656 - val_accuracy: 0.7536
Epoch 580/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4015 - accuracy: 0.8161 - val_loss: 0.4648 - val_accuracy: 0.7536
Epoch 581/1000
5/5 [==============================] - 0s 16ms/step - loss: 0.4019 - accuracy: 0.8000 - val_loss: 0.4649 - val_accuracy: 0.7571


5/5 [==============================] - 0s 10ms/step - loss: 0.3932 - accuracy: 0.8188 - val_loss: 0.4551 - val_accuracy: 0.7679
Epoch 633/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.3965 - accuracy: 0.8152 - val_loss: 0.4526 - val_accuracy: 0.7679
Epoch 634/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3931 - accuracy: 0.8161 - val_loss: 0.4508 - val_accuracy: 0.7679
Epoch 635/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3937 - accuracy: 0.8125 - val_loss: 0.4515 - val_accuracy: 0.7607
Epoch 636/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4013 - accuracy: 0.8196 - val_loss: 0.4552 - val_accuracy: 0.7500
Epoch 637/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.3949 - accuracy: 0.8116 - val_loss: 0.4519 - val_accuracy: 0.7679
Epoch 638/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3951 - accuracy: 0.8179 - val_loss: 0.4525 - val_accuracy: 0.7571
Epoch 639/1000
5/5

Epoch 690/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.3932 - accuracy: 0.8045 - val_loss: 0.4484 - val_accuracy: 0.7679
Epoch 691/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3891 - accuracy: 0.8196 - val_loss: 0.4466 - val_accuracy: 0.7643
Epoch 692/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.3898 - accuracy: 0.8223 - val_loss: 0.4497 - val_accuracy: 0.7714
Epoch 693/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.3903 - accuracy: 0.8250 - val_loss: 0.4527 - val_accuracy: 0.7500
Epoch 694/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3934 - accuracy: 0.8018 - val_loss: 0.4602 - val_accuracy: 0.7571
Epoch 695/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4004 - accuracy: 0.8152 - val_loss: 0.4476 - val_accuracy: 0.7750
Epoch 696/1000
5/5 [==============================] - 0s 23ms/step - loss: 0.3951 - accuracy: 0.8330 - val_loss: 0.4571 - val_accuracy: 0.7714
E

5/5 [==============================] - 0s 13ms/step - loss: 0.3960 - accuracy: 0.8241 - val_loss: 0.4479 - val_accuracy: 0.7536
Epoch 748/1000
5/5 [==============================] - 0s 14ms/step - loss: 0.4027 - accuracy: 0.7955 - val_loss: 0.4473 - val_accuracy: 0.7714
Epoch 749/1000
5/5 [==============================] - 0s 23ms/step - loss: 0.3883 - accuracy: 0.8214 - val_loss: 0.4439 - val_accuracy: 0.7607
Epoch 750/1000
5/5 [==============================] - 0s 12ms/step - loss: 0.3852 - accuracy: 0.8214 - val_loss: 0.4472 - val_accuracy: 0.7750
Epoch 751/1000
5/5 [==============================] - 0s 15ms/step - loss: 0.3871 - accuracy: 0.8277 - val_loss: 0.4465 - val_accuracy: 0.7679
Epoch 752/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3860 - accuracy: 0.8188 - val_loss: 0.4475 - val_accuracy: 0.7714
Epoch 753/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3973 - accuracy: 0.8321 - val_loss: 0.4589 - val_accuracy: 0.7714
Epoch 754/1000
5

5/5 [==============================] - 0s 9ms/step - loss: 0.3940 - accuracy: 0.8045 - val_loss: 0.4777 - val_accuracy: 0.7679
Epoch 805/1000
5/5 [==============================] - 0s 12ms/step - loss: 0.3928 - accuracy: 0.8295 - val_loss: 0.5092 - val_accuracy: 0.7607
Epoch 806/1000
5/5 [==============================] - 0s 12ms/step - loss: 0.4264 - accuracy: 0.7848 - val_loss: 0.4899 - val_accuracy: 0.7679
Epoch 807/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4099 - accuracy: 0.8161 - val_loss: 0.4560 - val_accuracy: 0.7750
Epoch 808/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3951 - accuracy: 0.8304 - val_loss: 0.4427 - val_accuracy: 0.7750
Epoch 809/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3968 - accuracy: 0.8018 - val_loss: 0.4474 - val_accuracy: 0.7786
Epoch 810/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3914 - accuracy: 0.8348 - val_loss: 0.4527 - val_accuracy: 0.7786
Epoch 811/1000
5/5

5/5 [==============================] - 0s 9ms/step - loss: 0.3912 - accuracy: 0.8268 - val_loss: 0.4446 - val_accuracy: 0.7571
Epoch 862/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.3867 - accuracy: 0.8259 - val_loss: 0.4405 - val_accuracy: 0.7679
Epoch 863/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3818 - accuracy: 0.8170 - val_loss: 0.4440 - val_accuracy: 0.7750
Epoch 864/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.3865 - accuracy: 0.8321 - val_loss: 0.4470 - val_accuracy: 0.7750
Epoch 865/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.3843 - accuracy: 0.8214 - val_loss: 0.4420 - val_accuracy: 0.7786
Epoch 866/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3818 - accuracy: 0.8313 - val_loss: 0.4443 - val_accuracy: 0.7679
Epoch 867/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.3819 - accuracy: 0.8223 - val_loss: 0.4414 - val_accuracy: 0.7821
Epoch 868/1000
5/5

5/5 [==============================] - 0s 10ms/step - loss: 0.3880 - accuracy: 0.8375 - val_loss: 0.4385 - val_accuracy: 0.7714
Epoch 919/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3883 - accuracy: 0.8161 - val_loss: 0.4419 - val_accuracy: 0.7750
Epoch 920/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3918 - accuracy: 0.8259 - val_loss: 0.4817 - val_accuracy: 0.7750
Epoch 921/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4016 - accuracy: 0.7920 - val_loss: 0.4646 - val_accuracy: 0.7821
Epoch 922/1000
5/5 [==============================] - 0s 20ms/step - loss: 0.4046 - accuracy: 0.8098 - val_loss: 0.4466 - val_accuracy: 0.7714
Epoch 923/1000
5/5 [==============================] - 0s 27ms/step - loss: 0.3837 - accuracy: 0.8250 - val_loss: 0.4453 - val_accuracy: 0.7857
Epoch 924/1000
5/5 [==============================] - 0s 13ms/step - loss: 0.3830 - accuracy: 0.8375 - val_loss: 0.4411 - val_accuracy: 0.7750
Epoch 925/1000
5/

5/5 [==============================] - 0s 10ms/step - loss: 0.3741 - accuracy: 0.8313 - val_loss: 0.4383 - val_accuracy: 0.7786
Epoch 976/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.3749 - accuracy: 0.8384 - val_loss: 0.4462 - val_accuracy: 0.7750
Epoch 977/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3817 - accuracy: 0.8241 - val_loss: 0.4372 - val_accuracy: 0.7893
Epoch 978/1000
5/5 [==============================] - 0s 22ms/step - loss: 0.3774 - accuracy: 0.8321 - val_loss: 0.4385 - val_accuracy: 0.7893
Epoch 979/1000
5/5 [==============================] - 0s 13ms/step - loss: 0.3768 - accuracy: 0.8384 - val_loss: 0.4403 - val_accuracy: 0.7821
Epoch 980/1000
5/5 [==============================] - 0s 12ms/step - loss: 0.3760 - accuracy: 0.8313 - val_loss: 0.4345 - val_accuracy: 0.7786
Epoch 981/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.3751 - accuracy: 0.8375 - val_loss: 0.4357 - val_accuracy: 0.7786
Epoch 982/1000


### Predicting

In [10]:
# Test the model after training
model_1.evaluate(X_test, Y_test, verbose=1)

19/19 [==============================] - 0s 2ms/step - loss: 0.4141 - accuracy: 0.8350


[0.4140760898590088, 0.8349999785423279]

We can see that our first model gave us validation accuracy of 83.50% which is very good.

# 2nd Model with two hidden layer with 16 neurons and 32 neurons.

### Creating Model

In [13]:
model_2 = Sequential()
model_2.add(Dense(8, input_shape=(8,), activation='relu'))
model_2.add(Dense(16, activation='relu'))
model_2.add(Dense(32, activation='relu'))
model_2.add(Dense(16, activation='relu'))
model_2.add(Dense(8, activation='relu'))
model_2.add(Dense(2, activation='softmax'))

### Configure the model and start training

In [14]:
model_2.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

### Training the model

In [15]:
model_2.fit(X_train, Y_train, epochs=1000, batch_size=250, verbose=1, validation_split=0.2)

Epoch 1/1000
5/5 [==============================] - 0s 82ms/step - loss: 40.1241 - accuracy: 0.6464 - val_loss: 26.0184 - val_accuracy: 0.6536
Epoch 2/1000
5/5 [==============================] - 0s 7ms/step - loss: 20.5652 - accuracy: 0.6411 - val_loss: 9.0394 - val_accuracy: 0.5429
Epoch 3/1000
5/5 [==============================] - 0s 9ms/step - loss: 10.1345 - accuracy: 0.4161 - val_loss: 12.0410 - val_accuracy: 0.3357
Epoch 4/1000
5/5 [==============================] - 0s 8ms/step - loss: 11.4197 - accuracy: 0.3509 - val_loss: 7.8894 - val_accuracy: 0.3429
Epoch 5/1000
5/5 [==============================] - 0s 8ms/step - loss: 6.8021 - accuracy: 0.3946 - val_loss: 5.1573 - val_accuracy: 0.5500
Epoch 6/1000
5/5 [==============================] - 0s 9ms/step - loss: 5.8344 - accuracy: 0.5312 - val_loss: 4.7689 - val_accuracy: 0.5821
Epoch 7/1000
5/5 [==============================] - 0s 8ms/step - loss: 4.2728 - accuracy: 0.5312 - val_loss: 2.7655 - val_accuracy: 0.4643
Epoch 8/1000


Epoch 59/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.6478 - accuracy: 0.6473 - val_loss: 0.6789 - val_accuracy: 0.6536
Epoch 60/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.6469 - accuracy: 0.6562 - val_loss: 0.6972 - val_accuracy: 0.6643
Epoch 61/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.6466 - accuracy: 0.6518 - val_loss: 0.6748 - val_accuracy: 0.6714
Epoch 62/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.6289 - accuracy: 0.6750 - val_loss: 0.6859 - val_accuracy: 0.6286
Epoch 63/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.6320 - accuracy: 0.6625 - val_loss: 0.6648 - val_accuracy: 0.6607
Epoch 64/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.6297 - accuracy: 0.6607 - val_loss: 0.6819 - val_accuracy: 0.6679
Epoch 65/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.6389 - accuracy: 0.6777 - val_loss: 0.6637 - val_accuracy: 0.6464
Epoch 66/1000

Epoch 117/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5450 - accuracy: 0.7223 - val_loss: 0.5895 - val_accuracy: 0.7071
Epoch 118/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.5519 - accuracy: 0.7196 - val_loss: 0.5897 - val_accuracy: 0.6964
Epoch 119/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5359 - accuracy: 0.7295 - val_loss: 0.6165 - val_accuracy: 0.6607
Epoch 120/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5438 - accuracy: 0.7277 - val_loss: 0.5929 - val_accuracy: 0.7000
Epoch 121/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.5474 - accuracy: 0.7223 - val_loss: 0.5863 - val_accuracy: 0.7107
Epoch 122/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.5381 - accuracy: 0.7321 - val_loss: 0.6047 - val_accuracy: 0.7107
Epoch 123/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.5669 - accuracy: 0.7054 - val_loss: 0.5793 - val_accuracy: 0.7107
Epo

5/5 [==============================] - 0s 14ms/step - loss: 0.4927 - accuracy: 0.7804 - val_loss: 0.5449 - val_accuracy: 0.7464
Epoch 175/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4931 - accuracy: 0.7812 - val_loss: 0.5431 - val_accuracy: 0.7393
Epoch 176/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4902 - accuracy: 0.7795 - val_loss: 0.5391 - val_accuracy: 0.7464
Epoch 177/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4906 - accuracy: 0.7732 - val_loss: 0.5366 - val_accuracy: 0.7429
Epoch 178/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4919 - accuracy: 0.7616 - val_loss: 0.5404 - val_accuracy: 0.7464
Epoch 179/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4948 - accuracy: 0.7768 - val_loss: 0.5411 - val_accuracy: 0.7500
Epoch 180/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4939 - accuracy: 0.7759 - val_loss: 0.5611 - val_accuracy: 0.7250
Epoch 181/1000
5/

5/5 [==============================] - 0s 8ms/step - loss: 0.4602 - accuracy: 0.7955 - val_loss: 0.5376 - val_accuracy: 0.7214
Epoch 232/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4711 - accuracy: 0.7821 - val_loss: 0.5535 - val_accuracy: 0.7286
Epoch 233/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4923 - accuracy: 0.7598 - val_loss: 0.5266 - val_accuracy: 0.7214
Epoch 234/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4740 - accuracy: 0.7750 - val_loss: 0.5748 - val_accuracy: 0.7321
Epoch 235/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4763 - accuracy: 0.7839 - val_loss: 0.5369 - val_accuracy: 0.7464
Epoch 236/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4625 - accuracy: 0.7982 - val_loss: 0.5339 - val_accuracy: 0.7321
Epoch 237/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4574 - accuracy: 0.7911 - val_loss: 0.5162 - val_accuracy: 0.7321
Epoch 238/1000
5/5 [=

5/5 [==============================] - 0s 17ms/step - loss: 0.4576 - accuracy: 0.7875 - val_loss: 0.5100 - val_accuracy: 0.7429
Epoch 289/1000
5/5 [==============================] - 0s 15ms/step - loss: 0.4506 - accuracy: 0.7920 - val_loss: 0.5102 - val_accuracy: 0.7500
Epoch 290/1000
5/5 [==============================] - 0s 13ms/step - loss: 0.4407 - accuracy: 0.8071 - val_loss: 0.5150 - val_accuracy: 0.7500
Epoch 291/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4428 - accuracy: 0.8036 - val_loss: 0.5139 - val_accuracy: 0.7679
Epoch 292/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4423 - accuracy: 0.8018 - val_loss: 0.5039 - val_accuracy: 0.7500
Epoch 293/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4444 - accuracy: 0.7946 - val_loss: 0.5335 - val_accuracy: 0.7536
Epoch 294/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4792 - accuracy: 0.7688 - val_loss: 0.5457 - val_accuracy: 0.7393
Epoch 295/1000
5

5/5 [==============================] - 0s 10ms/step - loss: 0.4398 - accuracy: 0.7973 - val_loss: 0.4915 - val_accuracy: 0.7643
Epoch 346/1000
5/5 [==============================] - 0s 13ms/step - loss: 0.4401 - accuracy: 0.7973 - val_loss: 0.5103 - val_accuracy: 0.7536
Epoch 347/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4403 - accuracy: 0.7982 - val_loss: 0.4979 - val_accuracy: 0.7571
Epoch 348/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4327 - accuracy: 0.7982 - val_loss: 0.5228 - val_accuracy: 0.7536
Epoch 349/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4453 - accuracy: 0.7937 - val_loss: 0.5416 - val_accuracy: 0.7464
Epoch 350/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4483 - accuracy: 0.7893 - val_loss: 0.5009 - val_accuracy: 0.7464
Epoch 351/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4517 - accuracy: 0.7777 - val_loss: 0.5175 - val_accuracy: 0.7500
Epoch 352/1000
5/5

5/5 [==============================] - 0s 10ms/step - loss: 0.4293 - accuracy: 0.8000 - val_loss: 0.4870 - val_accuracy: 0.7679
Epoch 403/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4348 - accuracy: 0.8018 - val_loss: 0.5094 - val_accuracy: 0.7464
Epoch 404/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4395 - accuracy: 0.7929 - val_loss: 0.4975 - val_accuracy: 0.7536
Epoch 405/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4182 - accuracy: 0.8009 - val_loss: 0.4970 - val_accuracy: 0.7607
Epoch 406/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.4306 - accuracy: 0.7991 - val_loss: 0.5253 - val_accuracy: 0.7536
Epoch 407/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4278 - accuracy: 0.8000 - val_loss: 0.4972 - val_accuracy: 0.7679
Epoch 408/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4223 - accuracy: 0.7982 - val_loss: 0.4876 - val_accuracy: 0.7607
Epoch 409/1000
5/5

5/5 [==============================] - 0s 13ms/step - loss: 0.4155 - accuracy: 0.8080 - val_loss: 0.4802 - val_accuracy: 0.7929
Epoch 460/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4168 - accuracy: 0.8152 - val_loss: 0.4836 - val_accuracy: 0.7714
Epoch 461/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4216 - accuracy: 0.7991 - val_loss: 0.4887 - val_accuracy: 0.7679
Epoch 462/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4073 - accuracy: 0.8152 - val_loss: 0.4752 - val_accuracy: 0.7821
Epoch 463/1000
5/5 [==============================] - 0s 25ms/step - loss: 0.4092 - accuracy: 0.8179 - val_loss: 0.4736 - val_accuracy: 0.7821
Epoch 464/1000
5/5 [==============================] - 0s 15ms/step - loss: 0.4168 - accuracy: 0.8098 - val_loss: 0.4813 - val_accuracy: 0.7750
Epoch 465/1000
5/5 [==============================] - 0s 19ms/step - loss: 0.4222 - accuracy: 0.8071 - val_loss: 0.5033 - val_accuracy: 0.7536
Epoch 466/1000

5/5 [==============================] - 0s 10ms/step - loss: 0.4113 - accuracy: 0.8054 - val_loss: 0.4987 - val_accuracy: 0.7643
Epoch 517/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4090 - accuracy: 0.8134 - val_loss: 0.4740 - val_accuracy: 0.7821
Epoch 518/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.3991 - accuracy: 0.8188 - val_loss: 0.4799 - val_accuracy: 0.7750
Epoch 519/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4019 - accuracy: 0.8152 - val_loss: 0.4660 - val_accuracy: 0.7893
Epoch 520/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4015 - accuracy: 0.8080 - val_loss: 0.4707 - val_accuracy: 0.7714
Epoch 521/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.3978 - accuracy: 0.8196 - val_loss: 0.4723 - val_accuracy: 0.7750
Epoch 522/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4038 - accuracy: 0.8098 - val_loss: 0.4700 - val_accuracy: 0.7893
Epoch 523/1000
5/5

5/5 [==============================] - 0s 9ms/step - loss: 0.4019 - accuracy: 0.8125 - val_loss: 0.4641 - val_accuracy: 0.7821
Epoch 574/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3990 - accuracy: 0.8107 - val_loss: 0.4633 - val_accuracy: 0.7893
Epoch 575/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3974 - accuracy: 0.8179 - val_loss: 0.4696 - val_accuracy: 0.7857
Epoch 576/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4021 - accuracy: 0.8161 - val_loss: 0.4627 - val_accuracy: 0.7750
Epoch 577/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3919 - accuracy: 0.8205 - val_loss: 0.4656 - val_accuracy: 0.7821
Epoch 578/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3986 - accuracy: 0.8232 - val_loss: 0.5030 - val_accuracy: 0.7571
Epoch 579/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4058 - accuracy: 0.8179 - val_loss: 0.4712 - val_accuracy: 0.7893
Epoch 580/1000
5/5 [

5/5 [==============================] - 0s 11ms/step - loss: 0.3874 - accuracy: 0.8170 - val_loss: 0.4674 - val_accuracy: 0.7714
Epoch 631/1000
5/5 [==============================] - 0s 21ms/step - loss: 0.3905 - accuracy: 0.8268 - val_loss: 0.4737 - val_accuracy: 0.7786
Epoch 632/1000
5/5 [==============================] - 0s 25ms/step - loss: 0.3862 - accuracy: 0.8286 - val_loss: 0.4693 - val_accuracy: 0.7786
Epoch 633/1000
5/5 [==============================] - 0s 15ms/step - loss: 0.3931 - accuracy: 0.8179 - val_loss: 0.4842 - val_accuracy: 0.7857
Epoch 634/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4015 - accuracy: 0.8143 - val_loss: 0.5209 - val_accuracy: 0.7571
Epoch 635/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4150 - accuracy: 0.8062 - val_loss: 0.4666 - val_accuracy: 0.7786
Epoch 636/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4021 - accuracy: 0.8232 - val_loss: 0.4942 - val_accuracy: 0.7679
Epoch 637/1000

5/5 [==============================] - 0s 9ms/step - loss: 0.3802 - accuracy: 0.8223 - val_loss: 0.4614 - val_accuracy: 0.7857
Epoch 688/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.3766 - accuracy: 0.8268 - val_loss: 0.4842 - val_accuracy: 0.7714
Epoch 689/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4101 - accuracy: 0.8143 - val_loss: 0.4593 - val_accuracy: 0.7857
Epoch 690/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4004 - accuracy: 0.8232 - val_loss: 0.4632 - val_accuracy: 0.7857
Epoch 691/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3841 - accuracy: 0.8205 - val_loss: 0.4571 - val_accuracy: 0.7821
Epoch 692/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.3834 - accuracy: 0.8313 - val_loss: 0.4768 - val_accuracy: 0.7821
Epoch 693/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3921 - accuracy: 0.8232 - val_loss: 0.5237 - val_accuracy: 0.7536
Epoch 694/1000
5/5 

5/5 [==============================] - 0s 12ms/step - loss: 0.3812 - accuracy: 0.8268 - val_loss: 0.4987 - val_accuracy: 0.7643
Epoch 745/1000
5/5 [==============================] - 0s 12ms/step - loss: 0.3958 - accuracy: 0.8125 - val_loss: 0.4649 - val_accuracy: 0.7964
Epoch 746/1000
5/5 [==============================] - 0s 13ms/step - loss: 0.3973 - accuracy: 0.8250 - val_loss: 0.4622 - val_accuracy: 0.7857
Epoch 747/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3806 - accuracy: 0.8321 - val_loss: 0.4599 - val_accuracy: 0.7857
Epoch 748/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.3723 - accuracy: 0.8357 - val_loss: 0.4647 - val_accuracy: 0.7893
Epoch 749/1000
5/5 [==============================] - 0s 12ms/step - loss: 0.3724 - accuracy: 0.8438 - val_loss: 0.4629 - val_accuracy: 0.7750
Epoch 750/1000
5/5 [==============================] - 0s 12ms/step - loss: 0.3831 - accuracy: 0.8286 - val_loss: 0.4548 - val_accuracy: 0.7893
Epoch 751/1000


Epoch 801/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.3806 - accuracy: 0.8366 - val_loss: 0.5191 - val_accuracy: 0.7679
Epoch 802/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.3998 - accuracy: 0.8134 - val_loss: 0.4744 - val_accuracy: 0.7821
Epoch 803/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4091 - accuracy: 0.8125 - val_loss: 0.4524 - val_accuracy: 0.8036
Epoch 804/1000
5/5 [==============================] - 0s 13ms/step - loss: 0.3869 - accuracy: 0.8143 - val_loss: 0.4839 - val_accuracy: 0.7786
Epoch 805/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.3876 - accuracy: 0.8223 - val_loss: 0.4795 - val_accuracy: 0.7750
Epoch 806/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.3789 - accuracy: 0.8393 - val_loss: 0.4663 - val_accuracy: 0.7821
Epoch 807/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.3882 - accuracy: 0.8393 - val_loss: 0.4769 - val_accuracy: 0.7857

5/5 [==============================] - 0s 12ms/step - loss: 0.3655 - accuracy: 0.8330 - val_loss: 0.4529 - val_accuracy: 0.7893
Epoch 859/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.3707 - accuracy: 0.8330 - val_loss: 0.4475 - val_accuracy: 0.7821
Epoch 860/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3654 - accuracy: 0.8313 - val_loss: 0.4459 - val_accuracy: 0.7929
Epoch 861/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3633 - accuracy: 0.8357 - val_loss: 0.4833 - val_accuracy: 0.7893
Epoch 862/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3829 - accuracy: 0.8304 - val_loss: 0.4587 - val_accuracy: 0.7857
Epoch 863/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3985 - accuracy: 0.8170 - val_loss: 0.5938 - val_accuracy: 0.7286
Epoch 864/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4653 - accuracy: 0.7821 - val_loss: 0.4924 - val_accuracy: 0.7893
Epoch 865/1000
5/5 

5/5 [==============================] - 0s 10ms/step - loss: 0.3608 - accuracy: 0.8375 - val_loss: 0.4566 - val_accuracy: 0.7857
Epoch 916/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.3622 - accuracy: 0.8420 - val_loss: 0.4535 - val_accuracy: 0.7857
Epoch 917/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3587 - accuracy: 0.8429 - val_loss: 0.4522 - val_accuracy: 0.8000
Epoch 918/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.3627 - accuracy: 0.8429 - val_loss: 0.4459 - val_accuracy: 0.7821
Epoch 919/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.3639 - accuracy: 0.8339 - val_loss: 0.4541 - val_accuracy: 0.7964
Epoch 920/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3622 - accuracy: 0.8321 - val_loss: 0.4624 - val_accuracy: 0.7821
Epoch 921/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3645 - accuracy: 0.8357 - val_loss: 0.4701 - val_accuracy: 0.7571
Epoch 922/1000
5/

5/5 [==============================] - 0s 9ms/step - loss: 0.3558 - accuracy: 0.8473 - val_loss: 0.4492 - val_accuracy: 0.7821
Epoch 973/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3556 - accuracy: 0.8393 - val_loss: 0.4523 - val_accuracy: 0.7893
Epoch 974/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.3541 - accuracy: 0.8375 - val_loss: 0.4736 - val_accuracy: 0.7821
Epoch 975/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.3671 - accuracy: 0.8402 - val_loss: 0.4483 - val_accuracy: 0.8000
Epoch 976/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3531 - accuracy: 0.8464 - val_loss: 0.4834 - val_accuracy: 0.7786
Epoch 977/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.3761 - accuracy: 0.8241 - val_loss: 0.4498 - val_accuracy: 0.7857
Epoch 978/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3599 - accuracy: 0.8491 - val_loss: 0.4742 - val_accuracy: 0.8071
Epoch 979/1000
5/5

### Predicting

In [16]:
# Test the model after training
model_2.evaluate(X_test, Y_test, verbose=1)

19/19 [==============================] - 0s 2ms/step - loss: 0.4492 - accuracy: 0.8050


[0.4492019712924957, 0.8050000071525574]

This model gaves us the validation accuracy of 80.50% which is less than model 1

# 3rd Model with three hidden layer with 16, 32 and 64 neurons.

### Creating Model

In [17]:
model_3 = Sequential()
model_3.add(Dense(8, input_shape=(8,), activation='relu'))
model_3.add(Dense(16, activation='relu'))
model_3.add(Dense(32, activation='relu'))
model_3.add(Dense(64, activation='relu'))
model_3.add(Dense(2, activation='softmax'))

### Configure the model and start training

In [18]:
model_3.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

### Training the model

In [19]:
model_3.fit(X_train, Y_train, epochs=1000, batch_size=250, verbose=1, validation_split=0.2)

Epoch 1/1000
5/5 [==============================] - 0s 79ms/step - loss: 6.0525 - accuracy: 0.4875 - val_loss: 2.9991 - val_accuracy: 0.3679
Epoch 2/1000
5/5 [==============================] - 0s 10ms/step - loss: 2.6723 - accuracy: 0.4500 - val_loss: 2.5045 - val_accuracy: 0.6036
Epoch 3/1000
5/5 [==============================] - 0s 8ms/step - loss: 2.1186 - accuracy: 0.6268 - val_loss: 1.4228 - val_accuracy: 0.5607
Epoch 4/1000
5/5 [==============================] - 0s 9ms/step - loss: 1.2355 - accuracy: 0.5714 - val_loss: 1.2793 - val_accuracy: 0.5786
Epoch 5/1000
5/5 [==============================] - 0s 8ms/step - loss: 1.2845 - accuracy: 0.5848 - val_loss: 1.0290 - val_accuracy: 0.5643
Epoch 6/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.9648 - accuracy: 0.6277 - val_loss: 1.0105 - val_accuracy: 0.6750
Epoch 7/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.9978 - accuracy: 0.6402 - val_loss: 0.9137 - val_accuracy: 0.5679
Epoch 8/1000
5/5 [

Epoch 59/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.5488 - accuracy: 0.7170 - val_loss: 0.5878 - val_accuracy: 0.6821
Epoch 60/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.5605 - accuracy: 0.7188 - val_loss: 0.6208 - val_accuracy: 0.6429
Epoch 61/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5682 - accuracy: 0.7196 - val_loss: 0.6138 - val_accuracy: 0.6571
Epoch 62/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5657 - accuracy: 0.7009 - val_loss: 0.6363 - val_accuracy: 0.6464
Epoch 63/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.5839 - accuracy: 0.6929 - val_loss: 0.5921 - val_accuracy: 0.6357
Epoch 64/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.5663 - accuracy: 0.7161 - val_loss: 0.5774 - val_accuracy: 0.7000
Epoch 65/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.5404 - accuracy: 0.7268 - val_loss: 0.5862 - val_accuracy: 0.7143
Epoch 66

5/5 [==============================] - 0s 10ms/step - loss: 0.5438 - accuracy: 0.7232 - val_loss: 0.5409 - val_accuracy: 0.7179
Epoch 117/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.5384 - accuracy: 0.7312 - val_loss: 0.5517 - val_accuracy: 0.6964
Epoch 118/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5127 - accuracy: 0.7446 - val_loss: 0.6229 - val_accuracy: 0.6786
Epoch 119/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.5385 - accuracy: 0.7393 - val_loss: 0.6164 - val_accuracy: 0.6571
Epoch 120/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.5162 - accuracy: 0.7536 - val_loss: 0.5684 - val_accuracy: 0.7357
Epoch 121/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.5025 - accuracy: 0.7545 - val_loss: 0.6198 - val_accuracy: 0.7000
Epoch 122/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5231 - accuracy: 0.7527 - val_loss: 0.5770 - val_accuracy: 0.7393
Epoch 123/1000
5/5 [

Epoch 174/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.6081 - accuracy: 0.7179 - val_loss: 0.5576 - val_accuracy: 0.7357
Epoch 175/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.5436 - accuracy: 0.7348 - val_loss: 0.6837 - val_accuracy: 0.6964
Epoch 176/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.5538 - accuracy: 0.7223 - val_loss: 0.5875 - val_accuracy: 0.7250
Epoch 177/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.5177 - accuracy: 0.7384 - val_loss: 0.5669 - val_accuracy: 0.7179
Epoch 178/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.5073 - accuracy: 0.7446 - val_loss: 0.5758 - val_accuracy: 0.6964
Epoch 179/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4895 - accuracy: 0.7688 - val_loss: 0.5572 - val_accuracy: 0.7107
Epoch 180/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.4778 - accuracy: 0.7607 - val_loss: 0.5354 - val_accuracy: 0.7393
Epoch

5/5 [==============================] - 0s 11ms/step - loss: 0.4503 - accuracy: 0.7714 - val_loss: 0.5095 - val_accuracy: 0.7607
Epoch 232/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4394 - accuracy: 0.7804 - val_loss: 0.5130 - val_accuracy: 0.7536
Epoch 233/1000
5/5 [==============================] - 0s 24ms/step - loss: 0.4387 - accuracy: 0.7848 - val_loss: 0.5073 - val_accuracy: 0.7536
Epoch 234/1000
5/5 [==============================] - 0s 15ms/step - loss: 0.4357 - accuracy: 0.7929 - val_loss: 0.5557 - val_accuracy: 0.7143
Epoch 235/1000
5/5 [==============================] - 0s 12ms/step - loss: 0.4522 - accuracy: 0.7902 - val_loss: 0.5060 - val_accuracy: 0.7536
Epoch 236/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4440 - accuracy: 0.7786 - val_loss: 0.5093 - val_accuracy: 0.7393
Epoch 237/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4603 - accuracy: 0.7696 - val_loss: 0.5246 - val_accuracy: 0.7607
Epoch 238/1000


5/5 [==============================] - 0s 12ms/step - loss: 0.4203 - accuracy: 0.7902 - val_loss: 0.5171 - val_accuracy: 0.7464
Epoch 289/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4310 - accuracy: 0.7884 - val_loss: 0.5081 - val_accuracy: 0.7393
Epoch 290/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4289 - accuracy: 0.8000 - val_loss: 0.5367 - val_accuracy: 0.7250
Epoch 291/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4492 - accuracy: 0.7795 - val_loss: 0.5378 - val_accuracy: 0.7107
Epoch 292/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4367 - accuracy: 0.7812 - val_loss: 0.5166 - val_accuracy: 0.7179
Epoch 293/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4253 - accuracy: 0.7893 - val_loss: 0.5222 - val_accuracy: 0.7393
Epoch 294/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4293 - accuracy: 0.7929 - val_loss: 0.5157 - val_accuracy: 0.7107
Epoch 295/1000
5/5 

Epoch 346/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4701 - accuracy: 0.7821 - val_loss: 0.5247 - val_accuracy: 0.7429
Epoch 347/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4444 - accuracy: 0.7937 - val_loss: 0.5126 - val_accuracy: 0.7429
Epoch 348/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4225 - accuracy: 0.8009 - val_loss: 0.5007 - val_accuracy: 0.7214
Epoch 349/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4077 - accuracy: 0.7920 - val_loss: 0.5083 - val_accuracy: 0.7571
Epoch 350/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4174 - accuracy: 0.8071 - val_loss: 0.5012 - val_accuracy: 0.7429
Epoch 351/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4096 - accuracy: 0.8062 - val_loss: 0.5099 - val_accuracy: 0.7429
Epoch 352/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4101 - accuracy: 0.7991 - val_loss: 0.4891 - val_accuracy: 0.7571
Epoch

5/5 [==============================] - 0s 9ms/step - loss: 0.4069 - accuracy: 0.8179 - val_loss: 0.4920 - val_accuracy: 0.7679
Epoch 404/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3997 - accuracy: 0.8116 - val_loss: 0.4876 - val_accuracy: 0.7607
Epoch 405/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.3954 - accuracy: 0.8170 - val_loss: 0.4912 - val_accuracy: 0.7464
Epoch 406/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.3994 - accuracy: 0.8062 - val_loss: 0.4951 - val_accuracy: 0.7679
Epoch 407/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.3967 - accuracy: 0.8116 - val_loss: 0.4918 - val_accuracy: 0.7464
Epoch 408/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.4030 - accuracy: 0.8062 - val_loss: 0.5061 - val_accuracy: 0.7536
Epoch 409/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4058 - accuracy: 0.8214 - val_loss: 0.5312 - val_accuracy: 0.7464
Epoch 410/1000
5/5 [=

Epoch 461/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3957 - accuracy: 0.8125 - val_loss: 0.4856 - val_accuracy: 0.7357
Epoch 462/1000
5/5 [==============================] - ETA: 0s - loss: 0.4294 - accuracy: 0.75 - 0s 8ms/step - loss: 0.3922 - accuracy: 0.8134 - val_loss: 0.5073 - val_accuracy: 0.7571
Epoch 463/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3991 - accuracy: 0.8009 - val_loss: 0.4874 - val_accuracy: 0.7393
Epoch 464/1000
5/5 [==============================] - 0s 20ms/step - loss: 0.3830 - accuracy: 0.8250 - val_loss: 0.4815 - val_accuracy: 0.7750
Epoch 465/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3819 - accuracy: 0.8214 - val_loss: 0.4808 - val_accuracy: 0.7679
Epoch 466/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3790 - accuracy: 0.8170 - val_loss: 0.4924 - val_accuracy: 0.7357
Epoch 467/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.3853 - accuracy: 0.8161 - va

5/5 [==============================] - 0s 11ms/step - loss: 0.3895 - accuracy: 0.8214 - val_loss: 0.5187 - val_accuracy: 0.7286
Epoch 519/1000
5/5 [==============================] - 0s 12ms/step - loss: 0.4075 - accuracy: 0.8045 - val_loss: 0.4951 - val_accuracy: 0.7536
Epoch 520/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4169 - accuracy: 0.8098 - val_loss: 0.5222 - val_accuracy: 0.7536
Epoch 521/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4197 - accuracy: 0.8009 - val_loss: 0.5426 - val_accuracy: 0.7429
Epoch 522/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4229 - accuracy: 0.8009 - val_loss: 0.5091 - val_accuracy: 0.7464
Epoch 523/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4057 - accuracy: 0.8062 - val_loss: 0.5109 - val_accuracy: 0.7429
Epoch 524/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4018 - accuracy: 0.8045 - val_loss: 0.4826 - val_accuracy: 0.7714
Epoch 525/1000
5

5/5 [==============================] - 0s 12ms/step - loss: 0.3747 - accuracy: 0.8205 - val_loss: 0.4889 - val_accuracy: 0.7250
Epoch 576/1000
5/5 [==============================] - 0s 17ms/step - loss: 0.3772 - accuracy: 0.8205 - val_loss: 0.5920 - val_accuracy: 0.6786
Epoch 577/1000
5/5 [==============================] - 0s 26ms/step - loss: 0.4352 - accuracy: 0.7893 - val_loss: 0.4966 - val_accuracy: 0.7393
Epoch 578/1000
5/5 [==============================] - 0s 25ms/step - loss: 0.3807 - accuracy: 0.8313 - val_loss: 0.4914 - val_accuracy: 0.7750
Epoch 579/1000
5/5 [==============================] - 0s 14ms/step - loss: 0.3660 - accuracy: 0.8259 - val_loss: 0.4711 - val_accuracy: 0.7500
Epoch 580/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.3656 - accuracy: 0.8259 - val_loss: 0.4874 - val_accuracy: 0.7536
Epoch 581/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.3727 - accuracy: 0.8286 - val_loss: 0.4649 - val_accuracy: 0.7679
Epoch 582/1000

5/5 [==============================] - 0s 10ms/step - loss: 0.3770 - accuracy: 0.8277 - val_loss: 0.4814 - val_accuracy: 0.7679
Epoch 633/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3474 - accuracy: 0.8402 - val_loss: 0.4663 - val_accuracy: 0.7821
Epoch 634/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.3465 - accuracy: 0.8500 - val_loss: 0.4666 - val_accuracy: 0.7714
Epoch 635/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3478 - accuracy: 0.8464 - val_loss: 0.4510 - val_accuracy: 0.7857
Epoch 636/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3478 - accuracy: 0.8393 - val_loss: 0.4718 - val_accuracy: 0.7607
Epoch 637/1000
5/5 [==============================] - 0s 14ms/step - loss: 0.3544 - accuracy: 0.8402 - val_loss: 0.4491 - val_accuracy: 0.7893
Epoch 638/1000
5/5 [==============================] - ETA: 0s - loss: 0.3472 - accuracy: 0.85 - 0s 11ms/step - loss: 0.3404 - accuracy: 0.8509 - val_loss: 0.458

5/5 [==============================] - 0s 10ms/step - loss: 0.3430 - accuracy: 0.8518 - val_loss: 0.4479 - val_accuracy: 0.7893
Epoch 690/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3333 - accuracy: 0.8509 - val_loss: 0.4758 - val_accuracy: 0.7750
Epoch 691/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.3352 - accuracy: 0.8616 - val_loss: 0.4977 - val_accuracy: 0.7786
Epoch 692/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.3494 - accuracy: 0.8518 - val_loss: 0.4419 - val_accuracy: 0.7786
Epoch 693/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.3322 - accuracy: 0.8536 - val_loss: 0.4937 - val_accuracy: 0.7679
Epoch 694/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3541 - accuracy: 0.8455 - val_loss: 0.4632 - val_accuracy: 0.7786
Epoch 695/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3483 - accuracy: 0.8518 - val_loss: 0.4668 - val_accuracy: 0.7714
Epoch 696/1000
5/

5/5 [==============================] - 0s 12ms/step - loss: 0.3378 - accuracy: 0.8473 - val_loss: 0.4435 - val_accuracy: 0.7929
Epoch 747/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.3330 - accuracy: 0.8598 - val_loss: 0.4507 - val_accuracy: 0.7786
Epoch 748/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.3211 - accuracy: 0.8545 - val_loss: 0.4507 - val_accuracy: 0.7929
Epoch 749/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3231 - accuracy: 0.8652 - val_loss: 0.4416 - val_accuracy: 0.8036
Epoch 750/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3228 - accuracy: 0.8589 - val_loss: 0.4474 - val_accuracy: 0.8071
Epoch 751/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3328 - accuracy: 0.8643 - val_loss: 0.4391 - val_accuracy: 0.8107
Epoch 752/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3207 - accuracy: 0.8643 - val_loss: 0.4349 - val_accuracy: 0.8036
Epoch 753/1000
5/5

Epoch 804/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.3272 - accuracy: 0.8589 - val_loss: 0.4494 - val_accuracy: 0.7857
Epoch 805/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.3230 - accuracy: 0.8616 - val_loss: 0.4453 - val_accuracy: 0.7893
Epoch 806/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.3141 - accuracy: 0.8696 - val_loss: 0.4395 - val_accuracy: 0.7786
Epoch 807/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.3117 - accuracy: 0.8723 - val_loss: 0.4787 - val_accuracy: 0.8000
Epoch 808/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3360 - accuracy: 0.8554 - val_loss: 0.4435 - val_accuracy: 0.8071
Epoch 809/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.3190 - accuracy: 0.8580 - val_loss: 0.4453 - val_accuracy: 0.7929
Epoch 810/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.3188 - accuracy: 0.8687 - val_loss: 0.4875 - val_accuracy: 0.7679
Epoch 

5/5 [==============================] - 0s 9ms/step - loss: 0.3079 - accuracy: 0.8723 - val_loss: 0.4464 - val_accuracy: 0.8143
Epoch 862/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.3087 - accuracy: 0.8750 - val_loss: 0.4904 - val_accuracy: 0.7893
Epoch 863/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.3202 - accuracy: 0.8670 - val_loss: 0.4360 - val_accuracy: 0.7893
Epoch 864/1000
5/5 [==============================] - 0s 12ms/step - loss: 0.3080 - accuracy: 0.8643 - val_loss: 0.5048 - val_accuracy: 0.7536
Epoch 865/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3337 - accuracy: 0.8536 - val_loss: 0.4606 - val_accuracy: 0.8036
Epoch 866/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3319 - accuracy: 0.8598 - val_loss: 0.5666 - val_accuracy: 0.7571
Epoch 867/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3807 - accuracy: 0.8446 - val_loss: 0.4870 - val_accuracy: 0.7714
Epoch 868/1000
5/5

5/5 [==============================] - 0s 19ms/step - loss: 0.2954 - accuracy: 0.8750 - val_loss: 0.4362 - val_accuracy: 0.8000
Epoch 919/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.2903 - accuracy: 0.8759 - val_loss: 0.4470 - val_accuracy: 0.7964
Epoch 920/1000
5/5 [==============================] - 0s 13ms/step - loss: 0.2977 - accuracy: 0.8670 - val_loss: 0.4413 - val_accuracy: 0.8071
Epoch 921/1000
5/5 [==============================] - 0s 17ms/step - loss: 0.2907 - accuracy: 0.8821 - val_loss: 0.4365 - val_accuracy: 0.8071
Epoch 922/1000
5/5 [==============================] - 0s 18ms/step - loss: 0.2884 - accuracy: 0.8813 - val_loss: 0.4360 - val_accuracy: 0.8071
Epoch 923/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.2925 - accuracy: 0.8705 - val_loss: 0.4507 - val_accuracy: 0.8036
Epoch 924/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.2984 - accuracy: 0.8687 - val_loss: 0.4368 - val_accuracy: 0.8321
Epoch 925/1000


5/5 [==============================] - 0s 13ms/step - loss: 0.2883 - accuracy: 0.8786 - val_loss: 0.4550 - val_accuracy: 0.7964
Epoch 976/1000
5/5 [==============================] - 0s 29ms/step - loss: 0.3021 - accuracy: 0.8696 - val_loss: 0.5003 - val_accuracy: 0.7607
Epoch 977/1000
5/5 [==============================] - 0s 37ms/step - loss: 0.3147 - accuracy: 0.8696 - val_loss: 0.4746 - val_accuracy: 0.8107
Epoch 978/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3258 - accuracy: 0.8536 - val_loss: 0.4564 - val_accuracy: 0.8036
Epoch 979/1000
5/5 [==============================] - 0s 20ms/step - loss: 0.2990 - accuracy: 0.8679 - val_loss: 0.4389 - val_accuracy: 0.8107
Epoch 980/1000
5/5 [==============================] - 0s 25ms/step - loss: 0.2809 - accuracy: 0.8813 - val_loss: 0.4609 - val_accuracy: 0.8036
Epoch 981/1000
5/5 [==============================] - 0s 12ms/step - loss: 0.2964 - accuracy: 0.8848 - val_loss: 0.4329 - val_accuracy: 0.8143
Epoch 982/1000


### Predicting

In [21]:
# Test the model after training
model_3.evaluate(X_test, Y_test, verbose=1)

19/19 [==============================] - 0s 1ms/step - loss: 0.4284 - accuracy: 0.8117


[0.4284043312072754, 0.8116666674613953]

This model has a very good training accur
acy but it gave us 81.17% validation accuracy which is again less than model 1 but better than model 2.

# 4th Model with three hidden layer with 16, 32 and 64 neurons.

### Creating Model

In [22]:
model_4 = Sequential()
model_4.add(Dense(8, input_shape=(8,), activation='relu'))
model_4.add(Dense(16, activation='relu'))
model_4.add(Dense(32, activation='relu'))
model_4.add(Dense(64, activation='relu'))
model_4.add(Dense(2, activation='softmax'))

In [23]:
optimizers = ["sgd",
              "rmsprop",
              "adam",
              "adadelta",
              "adagrad",
              "adamax",
              "nadam",
              "ftrl"]

### Model configuration, training and prediction using different optimizers.

In [24]:
for op in optimizers:
    
    print("Optimizer:",op)
    # Configure the model and start training
    model_4.compile(loss='categorical_crossentropy', optimizer=op, metrics=['accuracy'])
    
    # Fitting Model
    model_4.fit(X_train, Y_train, epochs=1000, batch_size=250, verbose=0, validation_split=0.2)


    # Test the model after training
    model_4.evaluate(X_test, Y_test, verbose=1)
    print("------------------------------------------------------------------------")

Optimizer: sgd
19/19 [==============================] - 0s 1ms/step - loss: 0.4553 - accuracy: 0.7983
------------------------------------------------------------------------
Optimizer: rmsprop
19/19 [==============================] - 0s 1ms/step - loss: 1.0344 - accuracy: 0.8450
------------------------------------------------------------------------
Optimizer: adam
19/19 [==============================] - 0s 2ms/step - loss: 1.1983 - accuracy: 0.8867
------------------------------------------------------------------------
Optimizer: adadelta
19/19 [==============================] - 0s 2ms/step - loss: 1.2003 - accuracy: 0.8967
------------------------------------------------------------------------
Optimizer: adagrad
19/19 [==============================] - 0s 2ms/step - loss: 1.2541 - accuracy: 0.8900
------------------------------------------------------------------------
Optimizer: adamax
19/19 [==============================] - 0s 1ms/step - loss: 2.1442 - accuracy: 0.8983
------

We can cleary see that adadela, adagrad, adamax and nadam outperform all other optimizers and adamax and nadam has the highest accuracy.

# 5th Model with three hidden layer with 16, 32 and 64 neurons.

### Creating Model

In [28]:
model_5 = Sequential()
model_5.add(Dense(8, input_shape=(8,), activation='relu'))
model_5.add(Dense(32, activation='relu'))
model_5.add(Dense(64, activation='relu'))
model_5.add(Dense(16, activation='relu'))
model_5.add(Dense(2, activation='softmax'))

### Configure the model and start training

In [29]:
model_5.compile(loss='categorical_crossentropy', optimizer='adamax', metrics=['accuracy'])

### Training the model

In [30]:
model_5.fit(X_train, Y_train, epochs=1000, batch_size=250, verbose=1, validation_split=0.2)

Epoch 1/1000
5/5 [==============================] - 0s 91ms/step - loss: 3.3597 - accuracy: 0.3536 - val_loss: 1.3592 - val_accuracy: 0.3464
Epoch 2/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.9129 - accuracy: 0.5223 - val_loss: 0.8459 - val_accuracy: 0.6571
Epoch 3/1000
5/5 [==============================] - 0s 9ms/step - loss: 1.0190 - accuracy: 0.6446 - val_loss: 0.9773 - val_accuracy: 0.6607
Epoch 4/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.9306 - accuracy: 0.6455 - val_loss: 0.6938 - val_accuracy: 0.6679
Epoch 5/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.6653 - accuracy: 0.6625 - val_loss: 0.6702 - val_accuracy: 0.6071
Epoch 6/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.7105 - accuracy: 0.5688 - val_loss: 0.7253 - val_accuracy: 0.5536
Epoch 7/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.7007 - accuracy: 0.5786 - val_loss: 0.6443 - val_accuracy: 0.6571
Epoch 8/1000
5/5 [

Epoch 59/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.5966 - accuracy: 0.7009 - val_loss: 0.5890 - val_accuracy: 0.7000
Epoch 60/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.5959 - accuracy: 0.7054 - val_loss: 0.5877 - val_accuracy: 0.7071
Epoch 61/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.5958 - accuracy: 0.7107 - val_loss: 0.5880 - val_accuracy: 0.7107
Epoch 62/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.5941 - accuracy: 0.7107 - val_loss: 0.5869 - val_accuracy: 0.7071
Epoch 63/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.5943 - accuracy: 0.7098 - val_loss: 0.5870 - val_accuracy: 0.7107
Epoch 64/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.5932 - accuracy: 0.7116 - val_loss: 0.5881 - val_accuracy: 0.7107
Epoch 65/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.5927 - accuracy: 0.7161 - val_loss: 0.5885 - val_accuracy: 0.7143
Epoch 66

Epoch 117/1000
5/5 [==============================] - 0s 12ms/step - loss: 0.5734 - accuracy: 0.7179 - val_loss: 0.5882 - val_accuracy: 0.6893
Epoch 118/1000
5/5 [==============================] - 0s 12ms/step - loss: 0.5737 - accuracy: 0.7161 - val_loss: 0.5902 - val_accuracy: 0.6893
Epoch 119/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.5725 - accuracy: 0.7196 - val_loss: 0.5905 - val_accuracy: 0.6929
Epoch 120/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.5722 - accuracy: 0.7188 - val_loss: 0.5896 - val_accuracy: 0.6964
Epoch 121/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.5718 - accuracy: 0.7170 - val_loss: 0.5896 - val_accuracy: 0.6857
Epoch 122/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.5717 - accuracy: 0.7188 - val_loss: 0.5888 - val_accuracy: 0.7036
Epoch 123/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.5710 - accuracy: 0.7161 - val_loss: 0.5918 - val_accuracy: 0.6750

5/5 [==============================] - 0s 11ms/step - loss: 0.5611 - accuracy: 0.7214 - val_loss: 0.5848 - val_accuracy: 0.6786
Epoch 175/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.5640 - accuracy: 0.7107 - val_loss: 0.5876 - val_accuracy: 0.6857
Epoch 176/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.5585 - accuracy: 0.7179 - val_loss: 0.5867 - val_accuracy: 0.6750
Epoch 177/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5584 - accuracy: 0.7223 - val_loss: 0.5870 - val_accuracy: 0.6857
Epoch 178/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5580 - accuracy: 0.7250 - val_loss: 0.5850 - val_accuracy: 0.6786
Epoch 179/1000
5/5 [==============================] - 0s 14ms/step - loss: 0.5579 - accuracy: 0.7277 - val_loss: 0.5859 - val_accuracy: 0.6786
Epoch 180/1000
5/5 [==============================] - 0s 14ms/step - loss: 0.5571 - accuracy: 0.7250 - val_loss: 0.5884 - val_accuracy: 0.6929
Epoch 181/1000
5

5/5 [==============================] - 0s 14ms/step - loss: 0.5453 - accuracy: 0.7268 - val_loss: 0.5844 - val_accuracy: 0.6643
Epoch 232/1000
5/5 [==============================] - 0s 17ms/step - loss: 0.5512 - accuracy: 0.7188 - val_loss: 0.5893 - val_accuracy: 0.6714
Epoch 233/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5436 - accuracy: 0.7348 - val_loss: 0.5854 - val_accuracy: 0.6821
Epoch 234/1000
5/5 [==============================] - 0s 6ms/step - loss: 0.5444 - accuracy: 0.7339 - val_loss: 0.5828 - val_accuracy: 0.6714
Epoch 235/1000
5/5 [==============================] - 0s 6ms/step - loss: 0.5454 - accuracy: 0.7312 - val_loss: 0.5885 - val_accuracy: 0.6607
Epoch 236/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.5451 - accuracy: 0.7357 - val_loss: 0.5853 - val_accuracy: 0.6786
Epoch 237/1000
5/5 [==============================] - 0s 6ms/step - loss: 0.5429 - accuracy: 0.7339 - val_loss: 0.5884 - val_accuracy: 0.6750
Epoch 238/1000
5/5 

5/5 [==============================] - 0s 8ms/step - loss: 0.5342 - accuracy: 0.7411 - val_loss: 0.5845 - val_accuracy: 0.6750
Epoch 289/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5265 - accuracy: 0.7420 - val_loss: 0.5812 - val_accuracy: 0.6893
Epoch 290/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5301 - accuracy: 0.7348 - val_loss: 0.5823 - val_accuracy: 0.6821
Epoch 291/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5286 - accuracy: 0.7536 - val_loss: 0.5844 - val_accuracy: 0.6679
Epoch 292/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.5285 - accuracy: 0.7393 - val_loss: 0.5812 - val_accuracy: 0.6929
Epoch 293/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.5286 - accuracy: 0.7518 - val_loss: 0.5866 - val_accuracy: 0.6714
Epoch 294/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.5298 - accuracy: 0.7429 - val_loss: 0.5847 - val_accuracy: 0.6857
Epoch 295/1000
5/5 [=

Epoch 346/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.5174 - accuracy: 0.7616 - val_loss: 0.5794 - val_accuracy: 0.7036
Epoch 347/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.5137 - accuracy: 0.7545 - val_loss: 0.5826 - val_accuracy: 0.6714
Epoch 348/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5178 - accuracy: 0.7473 - val_loss: 0.5795 - val_accuracy: 0.7071
Epoch 349/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.5164 - accuracy: 0.7554 - val_loss: 0.5776 - val_accuracy: 0.7107
Epoch 350/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.5119 - accuracy: 0.7634 - val_loss: 0.5809 - val_accuracy: 0.6893
Epoch 351/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.5123 - accuracy: 0.7545 - val_loss: 0.5762 - val_accuracy: 0.7179
Epoch 352/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.5127 - accuracy: 0.7554 - val_loss: 0.5776 - val_accuracy: 0.7143
Epoch

5/5 [==============================] - 0s 9ms/step - loss: 0.5048 - accuracy: 0.7625 - val_loss: 0.5755 - val_accuracy: 0.7214
Epoch 404/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5035 - accuracy: 0.7652 - val_loss: 0.5730 - val_accuracy: 0.7214
Epoch 405/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.5018 - accuracy: 0.7652 - val_loss: 0.5796 - val_accuracy: 0.6929
Epoch 406/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4991 - accuracy: 0.7679 - val_loss: 0.5754 - val_accuracy: 0.7071
Epoch 407/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4992 - accuracy: 0.7634 - val_loss: 0.5793 - val_accuracy: 0.6964
Epoch 408/1000
5/5 [==============================] - 0s 13ms/step - loss: 0.5006 - accuracy: 0.7652 - val_loss: 0.5730 - val_accuracy: 0.7250
Epoch 409/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4976 - accuracy: 0.7661 - val_loss: 0.5737 - val_accuracy: 0.7107
Epoch 410/1000
5/

5/5 [==============================] - 0s 11ms/step - loss: 0.4898 - accuracy: 0.7777 - val_loss: 0.5735 - val_accuracy: 0.7179
Epoch 461/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4877 - accuracy: 0.7759 - val_loss: 0.5786 - val_accuracy: 0.7250
Epoch 462/1000
5/5 [==============================] - 0s 12ms/step - loss: 0.4890 - accuracy: 0.7750 - val_loss: 0.5739 - val_accuracy: 0.7286
Epoch 463/1000
5/5 [==============================] - 0s 13ms/step - loss: 0.4870 - accuracy: 0.7768 - val_loss: 0.5812 - val_accuracy: 0.7179
Epoch 464/1000
5/5 [==============================] - 0s 13ms/step - loss: 0.4860 - accuracy: 0.7777 - val_loss: 0.5735 - val_accuracy: 0.7286
Epoch 465/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4856 - accuracy: 0.7750 - val_loss: 0.5747 - val_accuracy: 0.7250
Epoch 466/1000
5/5 [==============================] - 0s 17ms/step - loss: 0.4848 - accuracy: 0.7804 - val_loss: 0.5768 - val_accuracy: 0.7179
Epoch 467/1000

5/5 [==============================] - 0s 9ms/step - loss: 0.4759 - accuracy: 0.7893 - val_loss: 0.5699 - val_accuracy: 0.7429
Epoch 518/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4744 - accuracy: 0.7929 - val_loss: 0.5740 - val_accuracy: 0.7321
Epoch 519/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4761 - accuracy: 0.7929 - val_loss: 0.5688 - val_accuracy: 0.7357
Epoch 520/1000
5/5 [==============================] - ETA: 0s - loss: 0.4835 - accuracy: 0.78 - 0s 8ms/step - loss: 0.4779 - accuracy: 0.7839 - val_loss: 0.5679 - val_accuracy: 0.7321
Epoch 521/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4740 - accuracy: 0.7884 - val_loss: 0.5756 - val_accuracy: 0.7357
Epoch 522/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4743 - accuracy: 0.7911 - val_loss: 0.5678 - val_accuracy: 0.7393
Epoch 523/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4739 - accuracy: 0.7893 - val_loss: 0.5706 - 

5/5 [==============================] - 0s 7ms/step - loss: 0.4762 - accuracy: 0.7812 - val_loss: 0.5679 - val_accuracy: 0.7250
Epoch 575/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4692 - accuracy: 0.7839 - val_loss: 0.5783 - val_accuracy: 0.7143
Epoch 576/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4665 - accuracy: 0.7884 - val_loss: 0.5739 - val_accuracy: 0.7179
Epoch 577/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4642 - accuracy: 0.7937 - val_loss: 0.5729 - val_accuracy: 0.7286
Epoch 578/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4667 - accuracy: 0.7884 - val_loss: 0.5718 - val_accuracy: 0.7464
Epoch 579/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4671 - accuracy: 0.7893 - val_loss: 0.5675 - val_accuracy: 0.7464
Epoch 580/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4683 - accuracy: 0.7955 - val_loss: 0.5681 - val_accuracy: 0.7393
Epoch 581/1000
5/

5/5 [==============================] - 0s 10ms/step - loss: 0.4601 - accuracy: 0.7911 - val_loss: 0.5602 - val_accuracy: 0.7500
Epoch 632/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4571 - accuracy: 0.7964 - val_loss: 0.5671 - val_accuracy: 0.7286
Epoch 633/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4590 - accuracy: 0.7955 - val_loss: 0.5589 - val_accuracy: 0.7393
Epoch 634/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4600 - accuracy: 0.7875 - val_loss: 0.5638 - val_accuracy: 0.7429
Epoch 635/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4636 - accuracy: 0.7875 - val_loss: 0.5681 - val_accuracy: 0.7321
Epoch 636/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4644 - accuracy: 0.7884 - val_loss: 0.5588 - val_accuracy: 0.7429
Epoch 637/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4586 - accuracy: 0.7955 - val_loss: 0.5657 - val_accuracy: 0.7250
Epoch 638/1000

5/5 [==============================] - 0s 9ms/step - loss: 0.4581 - accuracy: 0.7848 - val_loss: 0.5619 - val_accuracy: 0.7250
Epoch 689/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4534 - accuracy: 0.7911 - val_loss: 0.5633 - val_accuracy: 0.7357
Epoch 690/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4525 - accuracy: 0.7955 - val_loss: 0.5577 - val_accuracy: 0.7536
Epoch 691/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4512 - accuracy: 0.7973 - val_loss: 0.5616 - val_accuracy: 0.7393
Epoch 692/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4510 - accuracy: 0.7946 - val_loss: 0.5572 - val_accuracy: 0.7321
Epoch 693/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4507 - accuracy: 0.7937 - val_loss: 0.5596 - val_accuracy: 0.7500
Epoch 694/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4502 - accuracy: 0.7982 - val_loss: 0.5593 - val_accuracy: 0.7321
Epoch 695/1000
5/5 

5/5 [==============================] - 0s 8ms/step - loss: 0.4486 - accuracy: 0.7973 - val_loss: 0.5535 - val_accuracy: 0.7393
Epoch 746/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4479 - accuracy: 0.7902 - val_loss: 0.5539 - val_accuracy: 0.7393
Epoch 747/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4434 - accuracy: 0.7964 - val_loss: 0.5637 - val_accuracy: 0.7393
Epoch 748/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4450 - accuracy: 0.7964 - val_loss: 0.5543 - val_accuracy: 0.7429
Epoch 749/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4492 - accuracy: 0.7902 - val_loss: 0.5523 - val_accuracy: 0.7429
Epoch 750/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4442 - accuracy: 0.7884 - val_loss: 0.5514 - val_accuracy: 0.7429
Epoch 751/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4528 - accuracy: 0.7839 - val_loss: 0.5498 - val_accuracy: 0.7464
Epoch 752/1000
5/5

5/5 [==============================] - 0s 11ms/step - loss: 0.4401 - accuracy: 0.7937 - val_loss: 0.5545 - val_accuracy: 0.7357
Epoch 803/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4385 - accuracy: 0.7973 - val_loss: 0.5504 - val_accuracy: 0.7286
Epoch 804/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4421 - accuracy: 0.7848 - val_loss: 0.5542 - val_accuracy: 0.7357
Epoch 805/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4368 - accuracy: 0.7911 - val_loss: 0.5525 - val_accuracy: 0.7500
Epoch 806/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4386 - accuracy: 0.7964 - val_loss: 0.5533 - val_accuracy: 0.7357
Epoch 807/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4384 - accuracy: 0.7929 - val_loss: 0.5479 - val_accuracy: 0.7536
Epoch 808/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4435 - accuracy: 0.7929 - val_loss: 0.5541 - val_accuracy: 0.7357
Epoch 809/1000

5/5 [==============================] - 0s 9ms/step - loss: 0.4381 - accuracy: 0.7929 - val_loss: 0.5484 - val_accuracy: 0.7464
Epoch 860/1000
5/5 [==============================] - 0s 12ms/step - loss: 0.4388 - accuracy: 0.7946 - val_loss: 0.5485 - val_accuracy: 0.7393
Epoch 861/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4390 - accuracy: 0.7911 - val_loss: 0.5455 - val_accuracy: 0.7500
Epoch 862/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4315 - accuracy: 0.7964 - val_loss: 0.5495 - val_accuracy: 0.7643
Epoch 863/1000
5/5 [==============================] - 0s 14ms/step - loss: 0.4301 - accuracy: 0.7955 - val_loss: 0.5489 - val_accuracy: 0.7357
Epoch 864/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4301 - accuracy: 0.7964 - val_loss: 0.5454 - val_accuracy: 0.7536
Epoch 865/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4310 - accuracy: 0.8000 - val_loss: 0.5457 - val_accuracy: 0.7464
Epoch 866/1000
5/

5/5 [==============================] - 0s 9ms/step - loss: 0.4331 - accuracy: 0.8045 - val_loss: 0.5475 - val_accuracy: 0.7536
Epoch 917/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4256 - accuracy: 0.7955 - val_loss: 0.5424 - val_accuracy: 0.7321
Epoch 918/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4296 - accuracy: 0.7991 - val_loss: 0.5454 - val_accuracy: 0.7536
Epoch 919/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4315 - accuracy: 0.7991 - val_loss: 0.5427 - val_accuracy: 0.7536
Epoch 920/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4271 - accuracy: 0.7991 - val_loss: 0.5421 - val_accuracy: 0.7500
Epoch 921/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4285 - accuracy: 0.8009 - val_loss: 0.5486 - val_accuracy: 0.7571
Epoch 922/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4258 - accuracy: 0.7973 - val_loss: 0.5431 - val_accuracy: 0.7429
Epoch 923/1000
5/5 

5/5 [==============================] - 0s 12ms/step - loss: 0.4210 - accuracy: 0.8071 - val_loss: 0.5419 - val_accuracy: 0.7500
Epoch 974/1000
5/5 [==============================] - 0s 12ms/step - loss: 0.4212 - accuracy: 0.7973 - val_loss: 0.5404 - val_accuracy: 0.7393
Epoch 975/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4213 - accuracy: 0.8036 - val_loss: 0.5438 - val_accuracy: 0.7500
Epoch 976/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4233 - accuracy: 0.7911 - val_loss: 0.5422 - val_accuracy: 0.7357
Epoch 977/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4199 - accuracy: 0.8027 - val_loss: 0.5480 - val_accuracy: 0.7571
Epoch 978/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4206 - accuracy: 0.8009 - val_loss: 0.5424 - val_accuracy: 0.7393
Epoch 979/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4241 - accuracy: 0.7982 - val_loss: 0.5429 - val_accuracy: 0.7321
Epoch 980/1000
5/5

### Predicting

In [31]:
# Test the model after training
model_5.evaluate(X_test, Y_test, verbose=1)

19/19 [==============================] - 0s 2ms/step - loss: 0.4462 - accuracy: 0.7967


[0.44617772102355957, 0.79666668176651]

Here, still model 1 outperforms with 83% accuracy as compared to 79.67% accuracy.

# 6th Model with three hidden layer

In [42]:
model_6 = Sequential()
model_6.add(Dense(8, input_shape=(8,), activation='relu'))
model_6.add(Dense(20, activation='relu'))
model_6.add(Dense(30, activation='relu'))
model_6.add(Dense(60, activation='relu'))
model_6.add(Dense(30, activation='relu'))
model_6.add(Dense(16, activation='relu'))
model_6.add(Dense(8, activation='relu'))
model_6.add(Dense(2, activation='softmax'))

### Model Configuration

In [43]:
model_6.compile(loss='categorical_crossentropy', optimizer='adamax', metrics=['accuracy'])

### Model Training

In [44]:
model_6.fit(X_train, Y_train, epochs=1000, batch_size=250, verbose=1, validation_split=0.2)

Epoch 1/1000
5/5 [==============================] - 0s 70ms/step - loss: 11.1545 - accuracy: 0.3536 - val_loss: 3.9158 - val_accuracy: 0.3786
Epoch 2/1000
5/5 [==============================] - 0s 8ms/step - loss: 2.0911 - accuracy: 0.5018 - val_loss: 1.7434 - val_accuracy: 0.6607
Epoch 3/1000
5/5 [==============================] - 0s 8ms/step - loss: 2.0562 - accuracy: 0.6464 - val_loss: 1.7400 - val_accuracy: 0.6607
Epoch 4/1000
5/5 [==============================] - 0s 7ms/step - loss: 1.4666 - accuracy: 0.6429 - val_loss: 0.9919 - val_accuracy: 0.4893
Epoch 5/1000
5/5 [==============================] - 0s 7ms/step - loss: 1.0252 - accuracy: 0.5018 - val_loss: 1.0469 - val_accuracy: 0.5107
Epoch 6/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.9197 - accuracy: 0.4786 - val_loss: 0.7416 - val_accuracy: 0.5179
Epoch 7/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.7344 - accuracy: 0.5982 - val_loss: 0.7367 - val_accuracy: 0.6857
Epoch 8/1000
5/5 [

Epoch 59/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5835 - accuracy: 0.7054 - val_loss: 0.6022 - val_accuracy: 0.7143
Epoch 60/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.5822 - accuracy: 0.7036 - val_loss: 0.5999 - val_accuracy: 0.7071
Epoch 61/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5816 - accuracy: 0.7089 - val_loss: 0.6002 - val_accuracy: 0.7107
Epoch 62/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5809 - accuracy: 0.7089 - val_loss: 0.6007 - val_accuracy: 0.7143
Epoch 63/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.5800 - accuracy: 0.7143 - val_loss: 0.5984 - val_accuracy: 0.7214
Epoch 64/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.5799 - accuracy: 0.7223 - val_loss: 0.5981 - val_accuracy: 0.7143
Epoch 65/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.5802 - accuracy: 0.7152 - val_loss: 0.5973 - val_accuracy: 0.7071
Epoch 66/100

Epoch 117/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5558 - accuracy: 0.7205 - val_loss: 0.5847 - val_accuracy: 0.7000
Epoch 118/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5563 - accuracy: 0.7143 - val_loss: 0.5814 - val_accuracy: 0.7107
Epoch 119/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.5552 - accuracy: 0.7321 - val_loss: 0.5816 - val_accuracy: 0.7179
Epoch 120/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5563 - accuracy: 0.7196 - val_loss: 0.5825 - val_accuracy: 0.6929
Epoch 121/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.5546 - accuracy: 0.7161 - val_loss: 0.5811 - val_accuracy: 0.7143
Epoch 122/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.5562 - accuracy: 0.7170 - val_loss: 0.5801 - val_accuracy: 0.7036
Epoch 123/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.5539 - accuracy: 0.7196 - val_loss: 0.5844 - val_accuracy: 0.6929
Epoch

5/5 [==============================] - 0s 7ms/step - loss: 0.5341 - accuracy: 0.7446 - val_loss: 0.5644 - val_accuracy: 0.7214
Epoch 175/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5337 - accuracy: 0.7348 - val_loss: 0.5644 - val_accuracy: 0.7071
Epoch 176/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.5310 - accuracy: 0.7348 - val_loss: 0.5625 - val_accuracy: 0.7179
Epoch 177/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5323 - accuracy: 0.7304 - val_loss: 0.5627 - val_accuracy: 0.7393
Epoch 178/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.5306 - accuracy: 0.7348 - val_loss: 0.5642 - val_accuracy: 0.7071
Epoch 179/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.5298 - accuracy: 0.7411 - val_loss: 0.5617 - val_accuracy: 0.7036
Epoch 180/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.5303 - accuracy: 0.7348 - val_loss: 0.5630 - val_accuracy: 0.6929
Epoch 181/1000
5/5 [=

Epoch 232/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.5101 - accuracy: 0.7527 - val_loss: 0.5456 - val_accuracy: 0.7179
Epoch 233/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5128 - accuracy: 0.7411 - val_loss: 0.5474 - val_accuracy: 0.7214
Epoch 234/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.5107 - accuracy: 0.7464 - val_loss: 0.5485 - val_accuracy: 0.7250
Epoch 235/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.5087 - accuracy: 0.7473 - val_loss: 0.5480 - val_accuracy: 0.7179
Epoch 236/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.5173 - accuracy: 0.7268 - val_loss: 0.5429 - val_accuracy: 0.7357
Epoch 237/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.5121 - accuracy: 0.7330 - val_loss: 0.5437 - val_accuracy: 0.7286
Epoch 238/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.5098 - accuracy: 0.7437 - val_loss: 0.5415 - val_accuracy: 0.7286
Epoch

5/5 [==============================] - 0s 9ms/step - loss: 0.4837 - accuracy: 0.7670 - val_loss: 0.5242 - val_accuracy: 0.7607
Epoch 290/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4868 - accuracy: 0.7607 - val_loss: 0.5267 - val_accuracy: 0.7429
Epoch 291/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4886 - accuracy: 0.7455 - val_loss: 0.5249 - val_accuracy: 0.7500
Epoch 292/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.4903 - accuracy: 0.7571 - val_loss: 0.5256 - val_accuracy: 0.7429
Epoch 293/1000
5/5 [==============================] - 0s 16ms/step - loss: 0.4860 - accuracy: 0.7518 - val_loss: 0.5228 - val_accuracy: 0.7500
Epoch 294/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4826 - accuracy: 0.7696 - val_loss: 0.5229 - val_accuracy: 0.7429
Epoch 295/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.4818 - accuracy: 0.7652 - val_loss: 0.5224 - val_accuracy: 0.7429
Epoch 296/1000
5/5 [

5/5 [==============================] - 0s 16ms/step - loss: 0.4653 - accuracy: 0.7741 - val_loss: 0.5060 - val_accuracy: 0.7500
Epoch 347/1000
5/5 [==============================] - 0s 13ms/step - loss: 0.4632 - accuracy: 0.7812 - val_loss: 0.5075 - val_accuracy: 0.7464
Epoch 348/1000
5/5 [==============================] - 0s 12ms/step - loss: 0.4638 - accuracy: 0.7768 - val_loss: 0.5037 - val_accuracy: 0.7571
Epoch 349/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4608 - accuracy: 0.7804 - val_loss: 0.5057 - val_accuracy: 0.7536
Epoch 350/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.4584 - accuracy: 0.7750 - val_loss: 0.5037 - val_accuracy: 0.7429
Epoch 351/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4586 - accuracy: 0.7830 - val_loss: 0.5057 - val_accuracy: 0.7500
Epoch 352/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4597 - accuracy: 0.7830 - val_loss: 0.5022 - val_accuracy: 0.7536
Epoch 353/1000


Epoch 404/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.4364 - accuracy: 0.8009 - val_loss: 0.4895 - val_accuracy: 0.7643
Epoch 405/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.4384 - accuracy: 0.7955 - val_loss: 0.4856 - val_accuracy: 0.7643
Epoch 406/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4445 - accuracy: 0.7830 - val_loss: 0.4888 - val_accuracy: 0.7536
Epoch 407/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4415 - accuracy: 0.7929 - val_loss: 0.4944 - val_accuracy: 0.7607
Epoch 408/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.4445 - accuracy: 0.7786 - val_loss: 0.5050 - val_accuracy: 0.7357
Epoch 409/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.4397 - accuracy: 0.7821 - val_loss: 0.4929 - val_accuracy: 0.7679
Epoch 410/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4422 - accuracy: 0.7795 - val_loss: 0.4878 - val_accuracy: 0.7679
Epoch

5/5 [==============================] - 0s 8ms/step - loss: 0.4336 - accuracy: 0.7911 - val_loss: 0.4830 - val_accuracy: 0.7571
Epoch 462/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4286 - accuracy: 0.7929 - val_loss: 0.4740 - val_accuracy: 0.7750
Epoch 463/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.4219 - accuracy: 0.8071 - val_loss: 0.4775 - val_accuracy: 0.7679
Epoch 464/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.4214 - accuracy: 0.7991 - val_loss: 0.4753 - val_accuracy: 0.7821
Epoch 465/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.4154 - accuracy: 0.8196 - val_loss: 0.4778 - val_accuracy: 0.7643
Epoch 466/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4238 - accuracy: 0.8018 - val_loss: 0.4764 - val_accuracy: 0.7607
Epoch 467/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4192 - accuracy: 0.7982 - val_loss: 0.4764 - val_accuracy: 0.7643
Epoch 468/1000
5/5 [=

Epoch 519/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.4071 - accuracy: 0.8054 - val_loss: 0.4802 - val_accuracy: 0.7679
Epoch 520/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4095 - accuracy: 0.8089 - val_loss: 0.4780 - val_accuracy: 0.7607
Epoch 521/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.4118 - accuracy: 0.8089 - val_loss: 0.4716 - val_accuracy: 0.7714
Epoch 522/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.4069 - accuracy: 0.8054 - val_loss: 0.4755 - val_accuracy: 0.7429
Epoch 523/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.4039 - accuracy: 0.8152 - val_loss: 0.4760 - val_accuracy: 0.7607
Epoch 524/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4055 - accuracy: 0.8179 - val_loss: 0.4726 - val_accuracy: 0.7714
Epoch 525/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.4068 - accuracy: 0.8062 - val_loss: 0.4700 - val_accuracy: 0.7643
Epoch 

5/5 [==============================] - 0s 9ms/step - loss: 0.3988 - accuracy: 0.8036 - val_loss: 0.4856 - val_accuracy: 0.7643
Epoch 577/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.4165 - accuracy: 0.7973 - val_loss: 0.5081 - val_accuracy: 0.7464
Epoch 578/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.4096 - accuracy: 0.7955 - val_loss: 0.4878 - val_accuracy: 0.7571
Epoch 579/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.4095 - accuracy: 0.8062 - val_loss: 0.4684 - val_accuracy: 0.7964
Epoch 580/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.3886 - accuracy: 0.8304 - val_loss: 0.4753 - val_accuracy: 0.7643
Epoch 581/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.3944 - accuracy: 0.8152 - val_loss: 0.4811 - val_accuracy: 0.7571
Epoch 582/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.3953 - accuracy: 0.8170 - val_loss: 0.4701 - val_accuracy: 0.7857
Epoch 583/1000
5/5 [=

5/5 [==============================] - 0s 8ms/step - loss: 0.3747 - accuracy: 0.8259 - val_loss: 0.4624 - val_accuracy: 0.7750
Epoch 634/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3736 - accuracy: 0.8268 - val_loss: 0.4648 - val_accuracy: 0.7786
Epoch 635/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.3734 - accuracy: 0.8295 - val_loss: 0.4634 - val_accuracy: 0.7750
Epoch 636/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3709 - accuracy: 0.8313 - val_loss: 0.4681 - val_accuracy: 0.7679
Epoch 637/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3734 - accuracy: 0.8295 - val_loss: 0.4708 - val_accuracy: 0.7714
Epoch 638/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.3820 - accuracy: 0.8268 - val_loss: 0.4728 - val_accuracy: 0.7679
Epoch 639/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3805 - accuracy: 0.8232 - val_loss: 0.4624 - val_accuracy: 0.7750
Epoch 640/1000
5/5 [=

Epoch 691/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3710 - accuracy: 0.8268 - val_loss: 0.4734 - val_accuracy: 0.7607
Epoch 692/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.3648 - accuracy: 0.8375 - val_loss: 0.4639 - val_accuracy: 0.7821
Epoch 693/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.3664 - accuracy: 0.8277 - val_loss: 0.4648 - val_accuracy: 0.7821
Epoch 694/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3649 - accuracy: 0.8321 - val_loss: 0.4652 - val_accuracy: 0.7786
Epoch 695/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.3630 - accuracy: 0.8366 - val_loss: 0.4747 - val_accuracy: 0.7679
Epoch 696/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.3641 - accuracy: 0.8321 - val_loss: 0.4632 - val_accuracy: 0.7786
Epoch 697/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3654 - accuracy: 0.8304 - val_loss: 0.4700 - val_accuracy: 0.7714
Epoch 

5/5 [==============================] - 0s 8ms/step - loss: 0.3549 - accuracy: 0.8321 - val_loss: 0.4704 - val_accuracy: 0.7786
Epoch 749/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3541 - accuracy: 0.8304 - val_loss: 0.4748 - val_accuracy: 0.7714
Epoch 750/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3510 - accuracy: 0.8366 - val_loss: 0.4676 - val_accuracy: 0.7786
Epoch 751/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3548 - accuracy: 0.8259 - val_loss: 0.4870 - val_accuracy: 0.7714
Epoch 752/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.3705 - accuracy: 0.8295 - val_loss: 0.4691 - val_accuracy: 0.7821
Epoch 753/1000
5/5 [==============================] - 0s 6ms/step - loss: 0.3504 - accuracy: 0.8384 - val_loss: 0.4785 - val_accuracy: 0.7679
Epoch 754/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.3511 - accuracy: 0.8375 - val_loss: 0.4793 - val_accuracy: 0.7679
Epoch 755/1000
5/5 [=

5/5 [==============================] - 0s 9ms/step - loss: 0.3466 - accuracy: 0.8366 - val_loss: 0.4817 - val_accuracy: 0.7786
Epoch 806/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.3446 - accuracy: 0.8429 - val_loss: 0.4949 - val_accuracy: 0.7750
Epoch 807/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.3459 - accuracy: 0.8348 - val_loss: 0.4985 - val_accuracy: 0.7714
Epoch 808/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3783 - accuracy: 0.8116 - val_loss: 0.4796 - val_accuracy: 0.7750
Epoch 809/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3704 - accuracy: 0.8286 - val_loss: 0.5089 - val_accuracy: 0.7500
Epoch 810/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3684 - accuracy: 0.8170 - val_loss: 0.4716 - val_accuracy: 0.7786
Epoch 811/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3496 - accuracy: 0.8366 - val_loss: 0.4718 - val_accuracy: 0.7750
Epoch 812/1000
5/5 [=

5/5 [==============================] - 0s 8ms/step - loss: 0.3399 - accuracy: 0.8393 - val_loss: 0.4783 - val_accuracy: 0.7929
Epoch 863/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.3352 - accuracy: 0.8473 - val_loss: 0.4786 - val_accuracy: 0.7821
Epoch 864/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3392 - accuracy: 0.8527 - val_loss: 0.4879 - val_accuracy: 0.7643
Epoch 865/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3408 - accuracy: 0.8384 - val_loss: 0.4781 - val_accuracy: 0.7929
Epoch 866/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3433 - accuracy: 0.8384 - val_loss: 0.4903 - val_accuracy: 0.7821
Epoch 867/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3452 - accuracy: 0.8384 - val_loss: 0.5140 - val_accuracy: 0.7643
Epoch 868/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3566 - accuracy: 0.8313 - val_loss: 0.4836 - val_accuracy: 0.7750
Epoch 869/1000
5/5 [=

Epoch 920/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3350 - accuracy: 0.8473 - val_loss: 0.4751 - val_accuracy: 0.7893
Epoch 921/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.3363 - accuracy: 0.8527 - val_loss: 0.4956 - val_accuracy: 0.7857
Epoch 922/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3444 - accuracy: 0.8348 - val_loss: 0.4927 - val_accuracy: 0.7679
Epoch 923/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.3261 - accuracy: 0.8473 - val_loss: 0.5603 - val_accuracy: 0.7464
Epoch 924/1000
5/5 [==============================] - 0s 6ms/step - loss: 0.3544 - accuracy: 0.8286 - val_loss: 0.4968 - val_accuracy: 0.7643
Epoch 925/1000
5/5 [==============================] - 0s 7ms/step - loss: 0.3412 - accuracy: 0.8455 - val_loss: 0.4920 - val_accuracy: 0.7679
Epoch 926/1000
5/5 [==============================] - 0s 6ms/step - loss: 0.3272 - accuracy: 0.8500 - val_loss: 0.4763 - val_accuracy: 0.7857
Epoch 

Epoch 978/1000
5/5 [==============================] - 0s 14ms/step - loss: 0.3256 - accuracy: 0.8411 - val_loss: 0.4895 - val_accuracy: 0.7857
Epoch 979/1000
5/5 [==============================] - 0s 11ms/step - loss: 0.3303 - accuracy: 0.8438 - val_loss: 0.4891 - val_accuracy: 0.7714
Epoch 980/1000
5/5 [==============================] - 0s 12ms/step - loss: 0.3213 - accuracy: 0.8571 - val_loss: 0.4827 - val_accuracy: 0.7821
Epoch 981/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.3223 - accuracy: 0.8509 - val_loss: 0.4805 - val_accuracy: 0.7821
Epoch 982/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.3242 - accuracy: 0.8527 - val_loss: 0.5052 - val_accuracy: 0.7786
Epoch 983/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.3262 - accuracy: 0.8491 - val_loss: 0.4880 - val_accuracy: 0.7821
Epoch 984/1000
5/5 [==============================] - 0s 9ms/step - loss: 0.3202 - accuracy: 0.8545 - val_loss: 0.5069 - val_accuracy: 0.7821


### Prediction

In [45]:
# Test the model after training
model_6.evaluate(X_test, Y_test, verbose=1)

19/19 [==============================] - 0s 4ms/step - loss: 0.4659 - accuracy: 0.8083


[0.46592843532562256, 0.8083333373069763]

### Conclusion
Here again, we can see that model 1 outperforms all other models with highest testing acuracy of 83%.